"""
Demo Bot - Chart Callback Handler

Handles: chart:*, view_chart
"""

import logging
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, Tuple

from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ContextTypes
from telegram.constants import ParseMode

logger = logging.getLogger(__name__)


async def handle_chart(
    ctx,
    action: str,
    data: str,
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
    state: Dict[str, Any],
) -> Tuple[str, InlineKeyboardMarkup]:
    """
    Handle chart callbacks.

    Args:
        ctx: DemoContextLoader instance
        action: The action
        data: Full callback data
        update: Telegram update
        context: Bot context
        state: Shared state dict

    Returns:
        Tuple of (text, keyboard)
    """
    theme = ctx.JarvisTheme
    DemoMenuBuilder = ctx.DemoMenuBuilder
    market_regime = state.get("market_regime", {})
    query = update.callback_query

    if action == "view_chart":
        try:
            from tg_bot.handlers.demo.demo_ui import MATPLOTLIB_AVAILABLE, generate_price_chart

            if not MATPLOTLIB_AVAILABLE:
                return DemoMenuBuilder.error_message(
                    error="Chart generation not available",
                    retry_action="demo:ai_report",
                    context_hint="Install matplotlib to enable charts: pip install matplotlib"
                )

            # Generate mock price data
            import random
            base_btc = 42000
            base_sol = 100
            hours = 24
            timestamps = [datetime.now(timezone.utc) - timedelta(hours=hours-i) for i in range(hours)]
            btc_prices = [base_btc + random.uniform(-2000, 2000) for _ in range(hours)]
            sol_prices = [base_sol + random.uniform(-5, 5) for _ in range(hours)]

            btc_chart = generate_price_chart(
                prices=btc_prices,
                timestamps=timestamps,
                symbol="BTC",
                timeframe="24H"
            )

            sol_chart = generate_price_chart(
                prices=sol_prices,
                timestamps=timestamps,
                symbol="SOL",
                timeframe="24H"
            )

            if btc_chart and sol_chart:
                await query.message.reply_photo(
                    photo=btc_chart,
                    caption=f"{theme.CHART} *Bitcoin (BTC) - 24H Price Chart*\n\n_Generated by JARVIS AI_",
                    parse_mode=ParseMode.MARKDOWN
                )
                await query.message.reply_photo(
                    photo=sol_chart,
                    caption=f"{theme.CHART} *Solana (SOL) - 24H Price Chart*\n\n_Generated by JARVIS AI_",
                    parse_mode=ParseMode.MARKDOWN
                )
                return DemoMenuBuilder.ai_report_menu(market_regime=market_regime)
            else:
                return DemoMenuBuilder.error_message(
                    error="Failed to generate charts",
                    retry_action="demo:view_chart",
                    context_hint="chart_generation"
                )
        except Exception as e:
            logger.error(f"Chart generation error: {e}", exc_info=True)
            from core.logging.error_tracker import error_tracker
            error_id = error_tracker.track_error(
                e,
                context=f"demo_callback action=view_chart",
                component="telegram_demo",
                metadata={"action": "view_chart"}
            )
            return DemoMenuBuilder.error_message(
                error=str(e)[:100],
                retry_action="demo:view_chart",
                context_hint=f"Error ID: {error_id}"
            )

    elif data.startswith("demo:chart:"):
        parts = data.split(":")
        token_ref = parts[2] if len(parts) > 2 else ""
        interval = parts[3] if len(parts) > 3 else "1h"

        token_addr = ctx.resolve_token_ref(context, token_ref)
        sentiment_data = await ctx.get_ai_sentiment_for_token(token_addr)
        token_symbol = sentiment_data.get("symbol", "TOKEN")

        # Show loading state
        try:
            await query.message.edit_text(
                theme.loading_text(f"Generating {token_symbol} chart"),
                parse_mode=ParseMode.MARKDOWN,
            )
        except Exception:
            pass

        try:
            from tg_bot.handlers.demo_charts import handle_chart_callback

            success, result = await handle_chart_callback(
                token_mint=token_addr,
                token_symbol=token_symbol,
                interval=interval,
            )

            if success:
                await context.bot.send_photo(
                    chat_id=query.message.chat_id,
                    photo=result,
                    caption=f"{theme.CHART} *{ctx.safe_symbol(token_symbol)}* Price Chart ({interval})",
                    parse_mode=ParseMode.MARKDOWN,
                )
                text = f"{theme.SUCCESS} Chart generated for *{ctx.safe_symbol(token_symbol)}*"
                keyboard = InlineKeyboardMarkup([
                    [
                        InlineKeyboardButton("1h", callback_data=f"demo:chart:{token_ref}:1h"),
                        InlineKeyboardButton("4h", callback_data=f"demo:chart:{token_ref}:4h"),
                        InlineKeyboardButton("1d", callback_data=f"demo:chart:{token_ref}:1d"),
                    ],
                    [
                        InlineKeyboardButton(f"{theme.BACK} Back", callback_data="demo:main"),
                    ],
                ])
                return text, keyboard
            else:
                return DemoMenuBuilder.error_message(result)
        except ImportError:
            return DemoMenuBuilder.error_message(
                "Chart feature requires mplfinance. Install with: pip install mplfinance pandas"
            )
        except Exception as e:
            logger.error(f"Chart generation error: {e}")
            return DemoMenuBuilder.error_message(f"Chart failed: {str(e)[:50]}")

    # Default
    return DemoMenuBuilder.ai_report_menu(market_regime=market_regime)
