import { NextResponse } from 'next/server';
import { apiRateLimiter, getClientIp } from '@/lib/rate-limiter';
import { evidenceTradesToCsv, getBacktestEvidence } from '@/lib/backtest-evidence';

// Evidence route reads from in-memory + disk cache (Node.js required).
export const runtime = 'nodejs';

/**
 * GET /api/backtest/evidence
 *
 * Downloads evidence artifacts generated by the most recent /api/backtest run
 * (cached server-side by runId).
 *
 * Query:
 * - runId: string (required)
 * - format: 'csv' | 'manifest' | 'report' | 'json' (default: 'csv')
 */
export async function GET(request: Request): Promise<NextResponse> {
  // Rate limit check (protects large downloads)
  const ip = getClientIp(request);
  const limit = apiRateLimiter.check(ip);
  if (!limit.allowed) {
    return NextResponse.json(
      { success: false, error: 'Rate limit exceeded' },
      {
        status: 429,
        headers: {
          'Retry-After': String(Math.ceil((limit.retryAfterMs || 60_000) / 1000)),
          'X-RateLimit-Remaining': '0',
        },
      },
    );
  }

  const url = new URL(request.url);
  const runId = url.searchParams.get('runId') || '';
  const format = (url.searchParams.get('format') || 'csv').toLowerCase();

  if (!runId) {
    return NextResponse.json({ success: false, error: 'Missing runId' }, { status: 400 });
  }

  const bundle = getBacktestEvidence(runId);
  if (!bundle) {
    return NextResponse.json(
      {
        success: false,
        error: 'Evidence not found (expired or unknown runId)',
      },
      { status: 404 },
    );
  }

  if (format === 'manifest') {
    return NextResponse.json({
      success: true,
      runId: bundle.runId,
      generatedAt: bundle.generatedAt,
      request: bundle.request,
      meta: bundle.meta,
      datasetCount: bundle.datasets.length,
      tradeCount: bundle.trades.length,
      datasets: bundle.datasets,
    });
  }

  if (format === 'report') {
    const md = bundle.reportMd || '# Backtest Report\n\n(no report was generated for this run)\n';
    const res = new NextResponse(md, {
      status: 200,
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="jarvis_backtest_report_${bundle.runId}.md"`,
      },
    });
    return res;
  }

  if (format === 'json') {
    return NextResponse.json({ success: true, evidence: bundle });
  }

  // Default: CSV
  const csv = evidenceTradesToCsv(bundle);
  const res = new NextResponse(csv, {
    status: 200,
    headers: {
      'Content-Type': 'text/csv; charset=utf-8',
      'Content-Disposition': `attachment; filename="jarvis_backtest_trades_${bundle.runId}.csv"`,
    },
  });
  return res;
}
