"""
MACD Strategy with Crossover Detection

Implements MACD-based trading signals including:
- MACD line crossover above/below signal line
- Histogram trend analysis (divergence)

Signals:
- MACD_BULLISH_CROSS: MACD crosses above signal line
- MACD_BEARISH_CROSS: MACD crosses below signal line
- MACD_HISTOGRAM_DIVERGENCE: Histogram showing trend change
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List, Dict, Any, Tuple

logger = logging.getLogger(__name__)


@dataclass
class MACDSignal:
    """
    Signal generated by MACD analysis.
    """
    signal_type: str  # MACD_BULLISH_CROSS, MACD_BEARISH_CROSS, etc.
    confidence: float
    direction: str  # long, short, neutral
    macd_value: float
    signal_line: float
    histogram: float
    has_crossover: bool
    crossover_direction: Optional[str]  # bullish, bearish, None
    histogram_trend: str  # increasing, decreasing, neutral
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> Dict[str, Any]:
        return {
            'signal_type': self.signal_type,
            'confidence': self.confidence,
            'direction': self.direction,
            'macd_value': self.macd_value,
            'signal_line': self.signal_line,
            'histogram': self.histogram,
            'has_crossover': self.has_crossover,
            'crossover_direction': self.crossover_direction,
            'histogram_trend': self.histogram_trend,
            'timestamp': self.timestamp.isoformat(),
        }


class MACDAnalyzer:
    """
    MACD analyzer with crossover and histogram divergence detection.

    Configuration:
        fast_period: Fast EMA period (default 12)
        slow_period: Slow EMA period (default 26)
        signal_period: Signal line EMA period (default 9)
        crossover_lookback: Periods to look back for crossovers (default 3)
    """

    def __init__(
        self,
        fast_period: int = 12,
        slow_period: int = 26,
        signal_period: int = 9,
        crossover_lookback: int = 3,
    ):
        self.fast_period = fast_period
        self.slow_period = slow_period
        self.signal_period = signal_period
        self.crossover_lookback = crossover_lookback

        # Price history
        self._prices: List[float] = []

        # EMA values
        self._fast_ema: Optional[float] = None
        self._slow_ema: Optional[float] = None
        self._signal_ema: Optional[float] = None

        # MACD history for crossover detection
        self._macd_history: List[float] = []
        self._signal_history: List[float] = []
        self._histogram_history: List[float] = []

        logger.info(
            f"MACDAnalyzer initialized: fast={fast_period}, "
            f"slow={slow_period}, signal={signal_period}"
        )

    def add_price(self, price: float) -> None:
        """Add a new price observation."""
        self._prices.append(price)

        # Calculate EMAs and MACD
        self._update_emas(price)

        # Keep history bounded
        max_history = self.slow_period * 3
        if len(self._prices) > max_history:
            self._prices = self._prices[-max_history:]

    def add_prices(self, prices: List[float]) -> None:
        """Add multiple price observations."""
        for price in prices:
            self.add_price(price)

    def _calculate_ema_multiplier(self, period: int) -> float:
        """Calculate EMA smoothing multiplier."""
        return 2.0 / (period + 1)

    def _update_emas(self, price: float) -> None:
        """Update EMA values with new price."""
        # Fast EMA
        if len(self._prices) < self.fast_period:
            self._fast_ema = None
        elif self._fast_ema is None:
            # Initialize with SMA
            self._fast_ema = sum(self._prices[-self.fast_period:]) / self.fast_period
        else:
            mult = self._calculate_ema_multiplier(self.fast_period)
            self._fast_ema = (price - self._fast_ema) * mult + self._fast_ema

        # Slow EMA
        if len(self._prices) < self.slow_period:
            self._slow_ema = None
        elif self._slow_ema is None:
            # Initialize with SMA
            self._slow_ema = sum(self._prices[-self.slow_period:]) / self.slow_period
        else:
            mult = self._calculate_ema_multiplier(self.slow_period)
            self._slow_ema = (price - self._slow_ema) * mult + self._slow_ema

        # Calculate MACD line
        if self._fast_ema is not None and self._slow_ema is not None:
            macd = self._fast_ema - self._slow_ema
            self._macd_history.append(macd)

            # Signal line (EMA of MACD)
            if len(self._macd_history) < self.signal_period:
                self._signal_ema = None
            elif self._signal_ema is None:
                self._signal_ema = sum(self._macd_history[-self.signal_period:]) / self.signal_period
            else:
                mult = self._calculate_ema_multiplier(self.signal_period)
                self._signal_ema = (macd - self._signal_ema) * mult + self._signal_ema

            if self._signal_ema is not None:
                self._signal_history.append(self._signal_ema)
                histogram = macd - self._signal_ema
                self._histogram_history.append(histogram)

            # Keep histories bounded
            max_history = self.slow_period * 2
            if len(self._macd_history) > max_history:
                self._macd_history = self._macd_history[-max_history:]
            if len(self._signal_history) > max_history:
                self._signal_history = self._signal_history[-max_history:]
            if len(self._histogram_history) > max_history:
                self._histogram_history = self._histogram_history[-max_history:]

    def get_macd_values(self) -> Tuple[Optional[float], Optional[float], Optional[float]]:
        """
        Get current MACD, signal line, and histogram values.

        Returns:
            Tuple of (MACD, Signal, Histogram)
        """
        if not self._macd_history or not self._signal_history:
            return None, None, None

        macd = self._macd_history[-1]
        signal = self._signal_history[-1]
        histogram = self._histogram_history[-1] if self._histogram_history else macd - signal

        return macd, signal, histogram

    def _detect_crossover(self) -> Tuple[bool, Optional[str]]:
        """
        Detect MACD/signal line crossover.

        Returns:
            Tuple of (has_crossover, direction)
        """
        if len(self._macd_history) < 2 or len(self._signal_history) < 2:
            return False, None

        # Compare current and previous positions
        prev_macd = self._macd_history[-2]
        curr_macd = self._macd_history[-1]
        prev_signal = self._signal_history[-2]
        curr_signal = self._signal_history[-1]

        # Bullish crossover: MACD crosses above signal
        if prev_macd <= prev_signal and curr_macd > curr_signal:
            return True, "bullish"

        # Bearish crossover: MACD crosses below signal
        if prev_macd >= prev_signal and curr_macd < curr_signal:
            return True, "bearish"

        return False, None

    def _analyze_histogram_trend(self) -> str:
        """
        Analyze histogram trend direction.

        Returns:
            'increasing', 'decreasing', or 'neutral'
        """
        if len(self._histogram_history) < 3:
            return "neutral"

        recent = self._histogram_history[-3:]

        # Check if histogram is consistently increasing or decreasing
        increasing = all(recent[i] > recent[i - 1] for i in range(1, len(recent)))
        decreasing = all(recent[i] < recent[i - 1] for i in range(1, len(recent)))

        if increasing:
            return "increasing"
        elif decreasing:
            return "decreasing"
        else:
            return "neutral"

    def analyze(self) -> MACDSignal:
        """
        Analyze current MACD state and detect signals.

        Returns:
            MACDSignal with signal type and details
        """
        macd, signal, histogram = self.get_macd_values()

        if macd is None or signal is None:
            return MACDSignal(
                signal_type="NO_SIGNAL",
                confidence=0.0,
                direction="neutral",
                macd_value=0.0,
                signal_line=0.0,
                histogram=0.0,
                has_crossover=False,
                crossover_direction=None,
                histogram_trend="neutral",
            )

        histogram = histogram if histogram is not None else 0.0
        has_crossover, crossover_dir = self._detect_crossover()
        histogram_trend = self._analyze_histogram_trend()

        # Determine signal type
        if has_crossover:
            if crossover_dir == "bullish":
                signal_type = "MACD_BULLISH_CROSS"
                direction = "long"
                confidence = 0.75
                logger.info(
                    f"MACD BULLISH CROSS: MACD={macd:.4f}, Signal={signal:.4f}"
                )
            else:
                signal_type = "MACD_BEARISH_CROSS"
                direction = "short"
                confidence = 0.75
                logger.info(
                    f"MACD BEARISH CROSS: MACD={macd:.4f}, Signal={signal:.4f}"
                )
        elif histogram_trend != "neutral":
            # Histogram divergence signal (weaker)
            signal_type = "MACD_HISTOGRAM_DIVERGENCE"
            if histogram_trend == "increasing":
                direction = "long"
            else:
                direction = "short"
            confidence = 0.6
            logger.info(
                f"MACD HISTOGRAM {histogram_trend.upper()}: Histogram={histogram:.4f}"
            )
        else:
            signal_type = "NO_SIGNAL"
            direction = "neutral"
            confidence = 0.0

        return MACDSignal(
            signal_type=signal_type,
            confidence=confidence,
            direction=direction,
            macd_value=macd,
            signal_line=signal,
            histogram=histogram,
            has_crossover=has_crossover,
            crossover_direction=crossover_dir,
            histogram_trend=histogram_trend,
        )

    def get_stats(self) -> Dict[str, Any]:
        """Get analyzer statistics."""
        macd, signal, histogram = self.get_macd_values()
        return {
            'macd_value': macd,
            'signal_line': signal,
            'histogram': histogram,
            'prices_tracked': len(self._prices),
            'macd_history_size': len(self._macd_history),
            'fast_period': self.fast_period,
            'slow_period': self.slow_period,
            'signal_period': self.signal_period,
        }
