"""
Revenue Tracker - Tracks all value generated.

Revenue sources:
1. Trading Profits - Actual crypto trading gains
2. Time Savings - Value of time saved by automation
3. Research Value - Knowledge generated (estimated)
4. Productivity Gains - Tasks completed automatically

Time savings valuation:
- User's hourly rate (configurable, default $50/hr)
- Time saved = tasks automated * avg manual time
"""

import json
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional

from core import config


ROOT = Path(__file__).resolve().parents[2]
REVENUE_DIR = ROOT / "data" / "economics"
REVENUE_LOG = REVENUE_DIR / "revenue.jsonl"


class RevenueCategory(str, Enum):
    TRADING = "trading"           # Crypto trading profits
    TIME_SAVED = "time_saved"     # Automation value
    RESEARCH = "research"         # Knowledge value
    PRODUCTIVITY = "productivity" # Task completion
    OTHER = "other"


# Default hourly rate for time value calculations
DEFAULT_HOURLY_RATE = 50.0  # USD


@dataclass
class RevenueEntry:
    """A single revenue entry."""
    timestamp: float
    category: RevenueCategory
    amount_usd: float
    description: str
    details: Dict[str, Any] = field(default_factory=dict)
    verified: bool = False  # True if actual $ received


@dataclass
class RevenueSummary:
    """Summary of revenue over a period."""
    period_start: float
    period_end: float
    total_usd: float
    by_category: Dict[str, float] = field(default_factory=dict)
    trading_pnl: float = 0.0
    time_saved_hours: float = 0.0
    verified_revenue: float = 0.0  # Actually received
    estimated_value: float = 0.0   # Time savings, etc.


class RevenueTracker:
    """
    Tracks all value generated by Jarvis.

    Usage:
        tracker = RevenueTracker()

        # Log trading profit
        tracker.log_trading_profit(
            profit_usd=150.0,
            trade_id="btc_123",
            strategy="momentum"
        )

        # Log time saved
        tracker.log_time_saved(
            minutes=30,
            task="email triage",
            agent="operator"
        )

        # Get summary
        summary = tracker.get_summary(days=7)
    """

    def __init__(self, hourly_rate: float = DEFAULT_HOURLY_RATE):
        REVENUE_DIR.mkdir(parents=True, exist_ok=True)
        self.hourly_rate = hourly_rate
        self._session_revenue: List[RevenueEntry] = []

    def log_trading_profit(
        self,
        profit_usd: float,
        trade_id: str = "",
        strategy: str = "",
        symbol: str = "",
        paper: bool = True,
    ) -> float:
        """
        Log trading profit or loss.

        Set paper=False for real trades.
        """
        entry = RevenueEntry(
            timestamp=time.time(),
            category=RevenueCategory.TRADING,
            amount_usd=profit_usd,
            description=f"{'Paper' if paper else 'Live'} trade: {symbol}",
            details={
                "trade_id": trade_id,
                "strategy": strategy,
                "symbol": symbol,
                "paper": paper,
            },
            verified=not paper,  # Only real trades are "verified"
        )

        self._log_entry(entry)
        return profit_usd

    def log_time_saved(
        self,
        minutes: float,
        task: str,
        agent: str = "",
    ) -> float:
        """
        Log time saved by automation.

        Returns the USD value of time saved.
        """
        hours = minutes / 60
        value = hours * self.hourly_rate

        entry = RevenueEntry(
            timestamp=time.time(),
            category=RevenueCategory.TIME_SAVED,
            amount_usd=value,
            description=f"Time saved: {task}",
            details={
                "minutes": minutes,
                "hours": hours,
                "task": task,
                "agent": agent,
                "hourly_rate": self.hourly_rate,
            },
            verified=False,  # Time savings are estimates
        )

        self._log_entry(entry)
        return value

    def log_research_value(
        self,
        value_usd: float,
        topic: str,
        output_type: str = "summary",
    ) -> float:
        """
        Log value of research output.

        This is an estimate - what would you pay for this research?
        """
        entry = RevenueEntry(
            timestamp=time.time(),
            category=RevenueCategory.RESEARCH,
            amount_usd=value_usd,
            description=f"Research: {topic}",
            details={
                "topic": topic,
                "output_type": output_type,
            },
            verified=False,
        )

        self._log_entry(entry)
        return value_usd

    def log_productivity(
        self,
        value_usd: float,
        task: str,
        agent: str = "",
    ) -> float:
        """Log productivity value (task completion)."""
        entry = RevenueEntry(
            timestamp=time.time(),
            category=RevenueCategory.PRODUCTIVITY,
            amount_usd=value_usd,
            description=f"Task completed: {task}",
            details={
                "task": task,
                "agent": agent,
            },
            verified=False,
        )

        self._log_entry(entry)
        return value_usd

    def log_other(
        self,
        amount_usd: float,
        description: str,
        verified: bool = False,
    ) -> float:
        """Log other revenue."""
        entry = RevenueEntry(
            timestamp=time.time(),
            category=RevenueCategory.OTHER,
            amount_usd=amount_usd,
            description=description,
            verified=verified,
        )

        self._log_entry(entry)
        return amount_usd

    def _log_entry(self, entry: RevenueEntry) -> None:
        """Write entry to log."""
        self._session_revenue.append(entry)

        log_data = {
            "timestamp": entry.timestamp,
            "category": entry.category.value,
            "amount_usd": entry.amount_usd,
            "description": entry.description,
            "verified": entry.verified,
            **entry.details,
        }

        with open(REVENUE_LOG, "a", encoding="utf-8") as f:
            f.write(json.dumps(log_data) + "\n")

        try:
            from core.economics.database import get_economics_db

            get_economics_db().record_revenue(
                category=entry.category.value,
                amount_usd=entry.amount_usd,
                description=entry.description,
                verified=entry.verified,
                details=entry.details,
            )
        except Exception:
            pass

    def get_summary(self, days: int = 1) -> RevenueSummary:
        """Get revenue summary for the last N days."""
        cutoff = time.time() - (days * 86400)

        by_category: Dict[str, float] = {}
        total = 0.0
        verified = 0.0
        estimated = 0.0
        trading_pnl = 0.0
        time_saved_hours = 0.0

        if REVENUE_LOG.exists():
            with open(REVENUE_LOG, "r") as f:
                for line in f:
                    try:
                        entry = json.loads(line)
                        if entry.get("timestamp", 0) < cutoff:
                            continue

                        amount = entry.get("amount_usd", 0)
                        category = entry.get("category", "other")
                        is_verified = entry.get("verified", False)

                        total += amount
                        by_category[category] = by_category.get(category, 0) + amount

                        if is_verified:
                            verified += amount
                        else:
                            estimated += amount

                        if category == "trading":
                            trading_pnl += amount

                        if category == "time_saved":
                            time_saved_hours += entry.get("hours", 0)

                    except json.JSONDecodeError:
                        continue

        return RevenueSummary(
            period_start=cutoff,
            period_end=time.time(),
            total_usd=total,
            by_category=by_category,
            trading_pnl=trading_pnl,
            time_saved_hours=time_saved_hours,
            verified_revenue=verified,
            estimated_value=estimated,
        )

    def get_today_revenue(self) -> float:
        """Quick accessor for today's revenue."""
        summary = self.get_summary(days=1)
        return summary.total_usd

    def get_session_revenue(self) -> float:
        """Get revenue for this session only."""
        return sum(e.amount_usd for e in self._session_revenue)


# Global instance
_revenue_tracker: Optional[RevenueTracker] = None


def get_revenue_tracker() -> RevenueTracker:
    """Get the global revenue tracker."""
    global _revenue_tracker
    if _revenue_tracker is None:
        _revenue_tracker = RevenueTracker()
    return _revenue_tracker


def log_revenue(
    category: str,
    amount_usd: float,
    description: str,
    **kwargs,
) -> float:
    """Convenience function to log revenue."""
    tracker = get_revenue_tracker()

    if category == "trading":
        return tracker.log_trading_profit(amount_usd, **kwargs)
    elif category == "time_saved":
        minutes = kwargs.get("minutes", amount_usd / (DEFAULT_HOURLY_RATE / 60))
        return tracker.log_time_saved(minutes, description, **kwargs)
    else:
        return tracker.log_other(amount_usd, description, **kwargs)
