#!/bin/bash
# Setup Cron Jobs for ClawdBot Automation
# Installs all scheduled tasks for backup, reflection, and monitoring

set -e

SCRIPT_DIR="/root/clawd/scripts"
LOG_DIR="/var/log"

echo "=========================================="
echo "Setting up ClawdBot Cron Jobs"
echo "=========================================="

# Create crontab entries
CRON_FILE="/tmp/clawdbot-cron"

cat > "$CRON_FILE" << EOF
# ClawdBot Automated Tasks
# Generated by setup-cron.sh

# Health watchdog - every minute
* * * * * /root/clawd/infra/bot-health-watchdog.sh >> $LOG_DIR/clawdbot-watchdog.log 2>&1

# Nightly backup - 3:00 AM UTC
0 3 * * * $SCRIPT_DIR/nightly-backup.sh >> $LOG_DIR/clawdbot-backup.log 2>&1

# Self-evolution reflection - 4:00 AM UTC
0 4 * * * $SCRIPT_DIR/self-evolution-reflect.sh >> $LOG_DIR/clawdbot-reflection.log 2>&1

# Redis hydration refresh - every 6 hours
0 */6 * * * $SCRIPT_DIR/redis-hydration.sh hydrate >> $LOG_DIR/clawdbot-hydration.log 2>&1

# Trust ladder status report - 8:00 AM UTC (daily)
0 8 * * * $SCRIPT_DIR/trust-ladder.sh status >> $LOG_DIR/clawdbot-trust.log 2>&1

# Circuit breaker status check - every 5 minutes
*/5 * * * * $SCRIPT_DIR/circuit-breaker.sh status > /tmp/circuit-breaker-status.json 2>&1

# Log rotation - midnight
0 0 * * * find $LOG_DIR -name "clawdbot-*.log" -mtime +7 -delete 2>/dev/null

# Weekly brain export (survival kit) - Sunday 2:00 AM
0 2 * * 0 for bot in friday matt jarvis; do $SCRIPT_DIR/brain-export.sh \$bot /root/clawd/backups/\$bot/weekly-brain.tar.gz; done >> $LOG_DIR/clawdbot-backup.log 2>&1
EOF

# Install crontab
crontab "$CRON_FILE"
rm "$CRON_FILE"

echo ""
echo "Cron jobs installed:"
crontab -l | grep -v "^#" | grep -v "^$"

echo ""
echo "=========================================="
echo "Cron setup complete"
echo "=========================================="
echo ""
echo "Log locations:"
echo "  Watchdog:   $LOG_DIR/clawdbot-watchdog.log"
echo "  Backup:     $LOG_DIR/clawdbot-backup.log"
echo "  Reflection: $LOG_DIR/clawdbot-reflection.log"
echo "  Trust:      $LOG_DIR/clawdbot-trust.log"
