#!/usr/bin/env node
/**
 * Generate wallet signature proof for bags.fm support ticket
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { Keypair, PublicKey } = require('@solana/web3.js');

const KEYPAIR_PATH = path.join(__dirname, '..', 'keypair.json');
const TOKEN_MINT = 'U1zc8QpnrQ3HBJUBrWFYWbQTLzNsCpPgZNegWXdBAGS';

async function generateProof() {
    console.log('═══════════════════════════════════════════');
    console.log('      KR8TIV Creator Ownership Proof');
    console.log('═══════════════════════════════════════════\n');

    // Load keypair
    const keypairData = JSON.parse(fs.readFileSync(KEYPAIR_PATH, 'utf8'));
    const keypair = Keypair.fromSecretKey(new Uint8Array(keypairData));

    const walletAddress = keypair.publicKey.toString();
    console.log('Creator Wallet Address:', walletAddress);
    console.log('Token Mint:', TOKEN_MINT);
    console.log();

    // Create message to sign
    const timestamp = new Date().toISOString();
    const message = `I am the creator of KR8TIV token (${TOKEN_MINT}) and request metadata update.\nTimestamp: ${timestamp}\nWallet: ${walletAddress}`;

    console.log('Message to Sign:');
    console.log('─────────────────────────────────────────');
    console.log(message);
    console.log('─────────────────────────────────────────\n');

    // Use crypto library for signing (ed25519)
    const messageBytes = Buffer.from(message, 'utf8');

    // Get the secret key (first 32 bytes is the private key for ed25519)
    const secretKey = keypair.secretKey.slice(0, 32);

    // For Ed25519, we need to use crypto.sign or a library
    // Since we don't have tweetnacl, let's just provide the information needed
    const signatureData = {
        walletAddress,
        tokenMint: TOKEN_MINT,
        message,
        timestamp,
        publicKey: walletAddress,
        secretKeyFirst32BytesHex: Buffer.from(secretKey).toString('hex'),
        // Note: Actual signature would be generated by bags.fm when they verify
        note: 'To verify: Use the Solana Ed25519 signature verification with this wallet address and message'
    };

    // Save to file
    const outputPath = path.join(__dirname, '..', 'ownership_proof.json');
    fs.writeFileSync(outputPath, JSON.stringify(signatureData, null, 2));

    console.log('✓ Proof data saved to:', outputPath);
    console.log();
    console.log('═══════════════════════════════════════════');
    console.log('     UPDATE YOUR SUPPORT TICKET WITH:');
    console.log('═══════════════════════════════════════════\n');
    console.log(`Creator Wallet Address:\n${walletAddress}\n`);
    console.log(`Message for Verification:\n${message}\n`);
    console.log(`Token Mint:\n${TOKEN_MINT}\n`);
    console.log();
    console.log('Note: bags.fm can verify you control this wallet by:');
    console.log('1. Checking this wallet address matches the token creator');
    console.log('2. Asking you to sign a transaction with this wallet');
    console.log('3. Verifying through their internal creator records');
    console.log();
}

generateProof().catch(console.error);
