import sys
from pydantic import BaseModel, Field
from typing import Optional, Literal

class PolicyEnvelope(BaseModel):
    """
    Generated by the MacroEngine (Slow).
    Dictates the bounds bounds over a longer time horizon (e.g. 1-4 hours).
    """
    bias: Literal["BULLISH", "BEARISH", "NEUTRAL"] = Field(..., description="Overall market bias.")
    max_lev: float = Field(..., description="Maximum allowed leverage for this envelope span.")
    validation_price: float = Field(..., description="Price at which this envelope is invalidated.")

class MacroEngine:
    def __init__(self):
        # In a real system, this would hold LangGraph configurations
        pass

    def generate_policy(self, market: str, current_price: float) -> PolicyEnvelope:
        """Mock behavior representing a slow 1-4 hour LLM calculation"""
        # Stand-in logic assuming LangGraph agent logic passed
        return PolicyEnvelope(
            bias="BULLISH",
            max_lev=2.0,
            validation_price=current_price * 0.90 # 10% drop invalidation
        )

async def breaking_news_check(market: str, xai_client=None) -> bool:
    """
    Returns True if safe to trade, False if breaking news detected.
    Used by the MicroEngine. Passes to Grok-4-1-fast-reasoning.
    """
    if xai_client is None:
        # Mock behavior for tests
        return True

    try:
        response = await xai_client.responses.create(
            model="grok-4-1-fast",
            tools=[{"type": "x_search"}],
            input=f"Is there any major breaking news about {market} in the last 5 minutes "
                  f"that would cause a significant price move? Respond with SAFE or DANGER only."
        )
        return "SAFE" in response.output_text.upper()
    except Exception:
        # Fail closed on network error to protect capital
        return False

class MicroEngine:
    def __init__(self, policy: PolicyEnvelope):
        self.active_policy = policy

    async def evaluate_tick(self, market: str, current_price: float, xai_client=None) -> bool:
        """
        Fast evaluation loop intended to run on sub-800ms websocket ticks.
        """
        if self.active_policy.bias == "NEUTRAL":
            return False

        if self.active_policy.bias == "BULLISH" and current_price < self.active_policy.validation_price:
            return False # Envelope invalidated

        if self.active_policy.bias == "BEARISH" and current_price > self.active_policy.validation_price:
            return False # Envelope invalidated

        # Perform fast DANGER check
        is_safe = await breaking_news_check(market, xai_client)
        return is_safe
