# Type stubs for solana package
from typing import Any, Optional, List, Dict

class Keypair:
    @classmethod
    def from_secret_key(cls, secret_key: bytes) -> "Keypair": ...
    @classmethod
    def generate(cls) -> "Keypair": ...
    @property
    def pubkey(self) -> "PublicKey": ...
    @property
    def secret_key(self) -> bytes: ...

class PublicKey:
    def __init__(self, value: str | bytes) -> None: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Transaction:
    def __init__(self) -> None: ...
    def add(self, *instructions: "TransactionInstruction") -> "Transaction": ...
    def sign(self, *signers: Keypair) -> None: ...
    def serialize(self) -> bytes: ...

class TransactionInstruction:
    program_id: PublicKey
    keys: List["AccountMeta"]
    data: bytes

class AccountMeta:
    pubkey: PublicKey
    is_signer: bool
    is_writable: bool

class Client:
    def __init__(self, endpoint: str) -> None: ...
    def get_balance(self, pubkey: PublicKey) -> Dict[str, Any]: ...
    def get_account_info(self, pubkey: PublicKey) -> Dict[str, Any]: ...
    def send_transaction(
        self,
        transaction: Transaction,
        *signers: Keypair
    ) -> Dict[str, Any]: ...
    def confirm_transaction(self, signature: str) -> Dict[str, Any]: ...
